# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0f3fcf1782871d6afa25e3600555a3b7496df81b274ef3591101afa3dadf6822883aeb3fe103ea7b7aa72f732b3bd2bfc5868b06114c64f4576a6e8e6d32ed6

test:
  secret_key_base: af9a7619a717a5866ade8aabe4d320690e4e13a1952d03f39c1bd0d709a3c6eef06da08b3e5378922ca1dc0d85d2dc42ac613b059c13d4564a0a0a58c22a9472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
